virtool/virtool-website

- content/docs/developer/frontend_resources.md
- update frontend resources pages for changes in libraries used and changes in library docs
> Update frontend resources

- content/docs/manual/gs_installation/index.md
- sample unit file
- instructions for starting and stopping a Virtool service
- instructions for running Virtool on system init
- fix formatting of some terminal samples
> Add information for creating systemd service

- content/docs/developer/api_otus.md
True/False values in the tables were inverted and made lowercase.
> Table headers changed from "Optional" to "Required"

- content/docs/manual/gs_configuration/index.md
- fix `proxy` description
- fix `db_connection_string` description
> Fix some configuration value descriptions

- assets/sass/code.sass
- content/docs/developer/frontend_testing/index.md
- layouts/shortcodes/administrator.html
- layouts/shortcodes/code_file.html
All requested changes are made. Let me know if something is missing or needs to be edited!
> Edits made to Frontend_testing

- assets/sass/docs.sass
- assets/sass/notes.sass
- assets/style.sass
- content/docs/manual/gs_configuration/index.md
- content/docs/manual/gs_installation/index.md
- content/docs/manual/gs_known_issues/index.md
- content/docs/manual/gs_mongo/index.md
- content/docs/manual/gs_setup/index.md
- add MongoDB 3.6 upgrade instructions
- separate MongoDB information to a separate section in _Getting Started_
> Add MongoDB section in 'Getting Started'

- content/netlify.toml
- add `netlify.toml`
- use HSTS and `X-Frame-Options` headers
> Add security headers

- content/docs/developer/api/labels.md
> Add labels section to API docs

- layouts/index.html
Change header alert for Virtool 5 site.
> Change header message to provisional

- content/docs/developer/api/samples.md
> Update Sample API docs

- content/docs/developer/api/hmm.md
- content/docs/developer/api/refs.md
- content/docs/developer/api/tasks.md
> Rename process to task in API docs 

- content/docs/manual/start/dependencies/index.md
> Fix FastQC link

- layouts/index.html
Prevents wrong release from being shown on landing page
> Pull landing page release info from releases4

- content/docs/developer/api/analyses.md
- content/docs/developer/api/samples.md
> Update API documentation for multiple subtractions

- content/docs/developer/api/labels.md
- content/docs/developer/api/refs.md
- content/docs/developer/api/uploads.md
Fix some issues and update to match recent changes to API.
> Update API docs

- content/docs/developer/job_api/analyses.md
Update Job API documentation to reflect endpoints created in virtool/virtool#2100
> Update analyses files documentation in Job API

- content/docs/developer/job_api/analyses.md
- content/docs/developer/job_api/hmm.md
- content/docs/developer/job_api/subtractions.md
> Add API documentation for new upload/download endpoints

- content/docs/developer/api/samples.md
- content/docs/developer/api/uploads.md
- content/docs/developer/job_api/analyses.md
- content/docs/developer/job_api/samples.md
- content/docs/developer/job_api/subtractions.md
> Add job API documentation for subtraction and sample finalization

- content/docs/developer/job_api/indexes.md
- content/docs/developer/job_api/subtractions.md
> Update index and subtraction Jobs API docs

- content/docs/developer/api/account.md
- content/docs/developer/api/analyses.md
- content/docs/developer/job_api/indexes.md
- content/docs/developer/job_api/jobs.md
- content/docs/developer/job_api/samples.md
- content/docs/developer/job_api/subtractions.md
> Update API endpoint documentation for analysis document download, sample reads and artifacts upload 

- content/docs/developer/job_api/samples.md
* Add missing upload and download endpoints.
* Make minor corrections to existing documentation.
> Update sample cache API documentation

- content/docs/developer/api/samples.md
* Add `group` input parameter and caveat about force group choice configuration.
* Update and add `subtractions` field.
> Update sample creation and editing API docs

- .gitignore
- layouts/index.html
This is out of date now.
Also, add `hugo_build.lock` to `.gitignore`.
> Remove version 4 banner

- content/docs/developer/frontend/testing/index.md
Adds section for RTL style tests
> update frontend testing guide
